spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
      # ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379

jwt:
  secretKey: tmffoaejdzm/vmfhsxm2aud/qordpsem2aud